### ISSUE TITLE
Handle mysql limitations

### ISSUE THREAD

**Issue by ketwaroo** [fmizzell/datastore#2]
This issues depends on the dataset being imported.

 - Field names can be too long. May need to truncate them to fit the mysql limit and add incrementing suffix to handle possible collisions

 - hitting maximum row size of 65,535 bytes. https://dev.mysql.com/doc/refman/8.0/en/column-count-limit.html. solution is to covert fields from `VARCHAR(255)` to `TEXT`

**Comment by fmizzell** [comment]
The second point was addressed here: https://github.com/fmizzell/datastore/commit/f2a67d4f14e8c8f28e999734cb608f5c600b4e9d

**Comment by fmizzell** [comment]
Dealing with the first issue: https://github.com/fmizzell/datastore/pull/3
